/**
 * Lineage Separation Guard
 *
 * Lineage = who TRAINED the base weights, not who hosts the model.
 * Llama-on-Groq is 'meta'. Qwen-on-Groq is 'alibaba'.
 *
 * FAIL CLOSED: unmapped model IDs throw — they never silently pass.
 * This prevents a new model being added and accidentally validating
 * its own family's claims.
 */

export type ModelLineage =
  | 'anthropic'  // Claude family
  | 'google'     // Gemini family
  | 'alibaba'    // Qwen family
  | 'meta'       // Llama family
  | 'mistral'    // Mistral / Mixtral family
  | 'xai'        // Grok family
  | 'perplexity' // Sonar (fine-tuned, RAG-augmented — distinct for validation purposes)
  | 'openai';    // GPT / o-series family

// ── Lineage map ───────────────────────────────────────────────────────────────
// Match on lowercased model ID prefix/substring.
// Order matters: more specific patterns first.

const LINEAGE_PATTERNS: Array<{ pattern: RegExp; lineage: ModelLineage }> = [
  // Anthropic / Claude
  { pattern: /^claude/, lineage: 'anthropic' },

  // Google / Gemini
  { pattern: /^gemini/, lineage: 'google' },

  // Alibaba / Qwen
  { pattern: /^qwen/, lineage: 'alibaba' },

  // Meta / Llama
  { pattern: /^llama/, lineage: 'meta' },
  { pattern: /^meta-llama/, lineage: 'meta' },

  // Mistral / Mixtral
  { pattern: /^mistral/, lineage: 'mistral' },
  { pattern: /^mixtral/, lineage: 'mistral' },
  { pattern: /^open-mistral/, lineage: 'mistral' },
  { pattern: /^open-mixtral/, lineage: 'mistral' },

  // xAI / Grok
  { pattern: /^grok/, lineage: 'xai' },

  // Perplexity / Sonar
  { pattern: /^sonar/, lineage: 'perplexity' },
  { pattern: /^pplx/, lineage: 'perplexity' },

  // OpenAI / GPT / o-series
  { pattern: /^gpt/, lineage: 'openai' },
  { pattern: /^o1/, lineage: 'openai' },
  { pattern: /^o3/, lineage: 'openai' },
  { pattern: /^o4/, lineage: 'openai' },
  { pattern: /^text-davinci/, lineage: 'openai' },

  // Provider name aliases (used when model is not specified)
  { pattern: /^claude$/, lineage: 'anthropic' },
  { pattern: /^gemini-flash$/, lineage: 'google' },
  { pattern: /^gemini$/, lineage: 'google' },
  { pattern: /^perplexity$/, lineage: 'perplexity' },
  { pattern: /^ollama$/, lineage: 'meta' }, // Ollama default = llama3.x
  { pattern: /^groq$/, lineage: 'alibaba' }, // Groq default = qwen (per GROQ_MODEL env)
];

/**
 * Returns the training lineage of a model.
 * Accepts both model IDs ("qwen-qwq-32b") and provider names ("groq").
 * FAIL CLOSED: throws for unrecognised models.
 */
export function lineageOf(modelId: string): ModelLineage {
  const lower = modelId.toLowerCase().trim();
  for (const { pattern, lineage } of LINEAGE_PATTERNS) {
    if (pattern.test(lower)) return lineage;
  }
  throw new Error(
    `[lineage] Unrecognised model: "${modelId}". ` +
    `Add it to LINEAGE_PATTERNS in lineage.ts before using it in the pipeline.`,
  );
}

/**
 * Asserts that two model IDs belong to different training lineages.
 * Throws if they share a lineage — the pipeline must never let the same
 * family both generate and validate the same claim.
 */
export function assertDifferentLineage(generatorModel: string, validatorModel: string): void {
  const gl = lineageOf(generatorModel);
  const vl = lineageOf(validatorModel);
  if (gl === vl) {
    throw new Error(
      `[lineage] Lineage violation: generator "${generatorModel}" and validator "${validatorModel}" ` +
      `both belong to the "${gl}" family. ` +
      `A model must never validate claims generated by its own family.`,
    );
  }
}

/**
 * Picks the best validator from a pool of model IDs, excluding any that
 * share a lineage with the generator.
 *
 * Priority: anthropic (Claude) > google (Gemini) > anything else.
 * Throws if no cross-lineage validator is available.
 */
const VALIDATOR_PRIORITY: ModelLineage[] = ['anthropic', 'google', 'perplexity', 'openai', 'mistral', 'meta', 'xai', 'alibaba'];

export function pickValidator(generatorModel: string, pool: string[]): string {
  const generatorLineage = lineageOf(generatorModel);

  const eligible = pool.filter((m) => {
    try {
      return lineageOf(m) !== generatorLineage;
    } catch {
      // Unmapped model — exclude it (fail closed)
      return false;
    }
  });

  if (eligible.length === 0) {
    throw new Error(
      `[lineage] No cross-lineage validator available for generator "${generatorModel}" (${generatorLineage}). ` +
      `Pool: [${pool.join(', ')}].`,
    );
  }

  // Sort by priority
  eligible.sort((a, b) => {
    const la = lineageOf(a);
    const lb = lineageOf(b);
    const pa = VALIDATOR_PRIORITY.indexOf(la);
    const pb = VALIDATOR_PRIORITY.indexOf(lb);
    return (pa === -1 ? 99 : pa) - (pb === -1 ? 99 : pb);
  });

  return eligible[0];
}
