import { jsonrepair } from 'jsonrepair';
import type { LLMResponse } from './types';

/**
 * Fixes mismatched brackets generated by LLMs — e.g. closing an object with ]
 * instead of } or an array with } instead of ].
 * Walks the string tracking a bracket stack and swaps closing brackets to match.
 */
function fixBracketMismatches(text: string): string {
  const stack: ('{' | '[')[] = [];
  let inString = false;
  let escaped = false;
  const chars = text.split('');

  for (let i = 0; i < chars.length; i++) {
    const c = chars[i];

    if (escaped) { escaped = false; continue; }
    if (c === '\\' && inString) { escaped = true; continue; }
    if (c === '"') { inString = !inString; continue; }
    if (inString) continue;

    if (c === '{' || c === '[') {
      stack.push(c as '{' | '[');
    } else if (c === '}' || c === ']') {
      const expected = stack[stack.length - 1] === '{' ? '}' : ']';
      if (stack.length > 0 && c !== expected) {
        chars[i] = expected; // swap the wrong bracket
      }
      if (stack.length > 0) stack.pop();
    }
  }

  return chars.join('');
}

/**
 * Extracts and parses JSON from an LLM response, handling:
 * - Markdown code fences
 * - Mismatched brackets (} vs ] confusion)
 * - jsonrepair for truncation and trailing commas
 */
export function parseJsonResponse(response: LLMResponse): unknown {
  if (response.parsed !== undefined) return response.parsed;

  const raw = response.text.trim();

  // Find start of JSON
  const start = Math.min(
    raw.indexOf('{') === -1 ? Infinity : raw.indexOf('{'),
    raw.indexOf('[') === -1 ? Infinity : raw.indexOf('['),
  );
  const slice = start !== Infinity ? raw.slice(start) : raw;

  // Attempt 1: bare JSON
  try { return JSON.parse(raw); } catch { /* continue */ }

  // Attempt 2: fix mismatched brackets then parse
  try { return JSON.parse(fixBracketMismatches(slice)); } catch { /* continue */ }

  // Attempt 3: jsonrepair on bracket-fixed text
  try { return JSON.parse(jsonrepair(fixBracketMismatches(slice))); } catch { /* continue */ }

  // Attempt 4: strip code fences
  const fenceMatch = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenceMatch) {
    const fenced = fenceMatch[1].trim();
    try { return JSON.parse(fenced); } catch { /* continue */ }
    try { return JSON.parse(fixBracketMismatches(fenced)); } catch { /* continue */ }
    try { return JSON.parse(jsonrepair(fenced)); } catch { /* continue */ }
  }

  // Attempt 5: jsonrepair directly
  if (start !== Infinity) {
    try { return JSON.parse(jsonrepair(slice)); } catch { /* continue */ }
  }

  throw new Error(
    `JSON parse failed — could not extract valid JSON. ` +
      `Response started with: ${raw.slice(0, 120)}`,
  );
}
