/**
 * POST /api/admin/images/generate-hero
 *
 * Body: { topic: string }
 *
 * Flow:
 *   1. Load dossier (title, driving_question, synthesized_output/summary)
 *   2. Grok generates 4 image prompts (Literal, Symbolic, Environmental, Detail)
 *   3. Calls xAI Grok Imagine for each prompt — sequentially to respect rate limits
 *   4. Uploads each image to Supabase Storage (topic-images bucket)
 *   5. Inserts into topic_images with source='grok_generated', status='suggested'
 *
 * Returns: { ok, generated, prompts, images, errors? }
 */

import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabaseClient } from '@/lib/supabase';
import { requireAdmin } from '@/lib/auth';
import { generateHeroPrompts } from '@/lib/media/hero-prompt-generator';
import { generateImage } from '@/lib/external/grok-image';

export const maxDuration = 300;

export async function POST(req: NextRequest) {
  const { error: authError } = await requireAdmin();
  if (authError) return authError;

  const { topic } = await req.json() as { topic?: string };
  if (!topic) return NextResponse.json({ error: 'topic required' }, { status: 400 });

  const supabase = createServerSupabaseClient();

  // Load dossier
  const { data: dossier, error: dossierError } = await supabase
    .from('topic_dossiers')
    .select('title, driving_question, synthesized_output, summary')
    .eq('topic', topic)
    .single();

  if (dossierError || !dossier) {
    return NextResponse.json({ error: 'Dossier not found' }, { status: 404 });
  }

  const title = (dossier.title as string | null) ?? topic;
  const drivingQuestion = dossier.driving_question as string | null;

  // Build article summary from synthesized_output or fall back to summary
  const synOutput = dossier.synthesized_output as Record<string, unknown> | null;
  const articleSummary =
    (synOutput?.executive_summary as string | undefined) ??
    (synOutput?.synthesis as string | undefined) ??
    (dossier.summary as string | null) ??
    title;

  // Step 1 — Generate prompts with Grok
  let prompts;
  try {
    prompts = await generateHeroPrompts(topic, title, drivingQuestion, articleSummary);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error('[generate-hero] prompt generation failed:', msg);
    return NextResponse.json({ error: `Prompt generation failed: ${msg}` }, { status: 500 });
  }
  if (prompts.length === 0) {
    return NextResponse.json({ error: 'Grok returned no prompts — check XAI_IMAGE_API_KEY and model availability' }, { status: 500 });
  }

  // Step 2 — Generate images sequentially (xAI rate limits)
  const results: { id: string; url: string; type: string; prompt: string }[] = [];
  const errors: string[] = [];

  for (const heroPrompt of prompts) {
    try {
      const imageResult = await generateImage(heroPrompt.prompt);

      // Upload to Supabase Storage
      const imageBytes = Buffer.from(imageResult.b64_json, 'base64');
      const slug = topic.replace(/[^a-z0-9-]/gi, '_');
      const storagePath = `${slug}/ai_${heroPrompt.type}_${Date.now()}.png`;

      const { error: uploadError } = await supabase.storage
        .from('topic-images')
        .upload(storagePath, imageBytes, { contentType: 'image/png', upsert: false });

      if (uploadError) {
        errors.push(`${heroPrompt.type}: upload failed — ${uploadError.message}`);
        continue;
      }

      const { data: { publicUrl } } = supabase.storage
        .from('topic-images')
        .getPublicUrl(storagePath);

      // Insert into topic_images
      const { data: inserted, error: dbError } = await supabase
        .from('topic_images')
        .insert({
          topic,
          source: 'grok_generated',
          search_query: heroPrompt.type,
          title: `${heroPrompt.label} — AI Hero`,
          description: heroPrompt.prompt.slice(0, 500),
          image_url: publicUrl,
          thumbnail_url: publicUrl,
          source_page_url: null,
          license: 'AI Generated',
          license_url: null,
          attribution: 'Generated by xAI Grok Imagine for UnraveledTruth.com',
          author: 'Grok Imagine / xAI',
          date_created: new Date().toISOString().slice(0, 10),
          width: 1024,
          height: 1024,
          mime_type: 'image/png',
          quality_score: 0.85,
          status: 'suggested',
          featured: false,
          gemini_verdict: null,
          gemini_caption: null,
          gemini_literal: heroPrompt.prompt.slice(0, 300),
          updated_at: new Date().toISOString(),
        })
        .select('id')
        .single();

      if (dbError) {
        errors.push(`${heroPrompt.type}: DB error — ${dbError.message}`);
        await supabase.storage.from('topic-images').remove([storagePath]);
        continue;
      }

      results.push({ id: inserted.id, url: publicUrl, type: heroPrompt.type, prompt: heroPrompt.prompt });
    } catch (err) {
      errors.push(`${heroPrompt.type}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  return NextResponse.json({
    ok: results.length > 0,
    generated: results.length,
    prompts: prompts.map((p) => ({ type: p.type, label: p.label, prompt: p.prompt })),
    images: results,
    ...(errors.length > 0 ? { errors } : {}),
  });
}
