import type { VizNarrative } from '../types';

export const FLOOD_NARRATIVES: VizNarrative[] = [
  // ── Geological ───────────────────────────────────────────────────────────
  { id: 'blacksea', lat: 42.5, lng: 34.0, year: -5600, title: 'Black Sea Deluge', region: 'Black Sea Basin', type: 'geological', tradition: 'Geological Record', desc: 'Mediterranean breaches the Bosporus strait, catastrophically flooding the freshwater Black Sea basin. Sediment cores confirm abrupt saltwater incursion c. 5600 BCE.', source: 'Ryan & Pitman, 1998', radius: 4 },
  { id: 'storegga', lat: 63.0, lng: 3.0, year: -6100, title: 'Storegga Slide Megatsunami', region: 'Norwegian Sea', type: 'geological', tradition: 'Geological Record', desc: 'Massive submarine landslide off Norway triggers a megatsunami inundating coastal Europe. Doggerland — the inhabited landmass connecting Britain to Europe — was flooded.', source: 'Bondevik et al., 2005', radius: 3 },
  { id: 'yellowriver', lat: 35.5, lng: 105.0, year: -1920, title: 'Yellow River Outburst Flood', region: 'Qinghai, China', type: 'geological', tradition: 'Geological Record', desc: 'Geological evidence of a catastrophic outburst flood on the Yellow River — one of the largest freshwater floods in 10,000 years. Corroborates Chinese dynastic flood records.', source: 'Wu et al., Science, 2016', radius: 4 },
  { id: 'meltwater', lat: 55.0, lng: -20.0, year: -9700, title: 'Meltwater Pulse 1A', region: 'North Atlantic', type: 'geological', tradition: 'Geological Record', desc: 'Global sea levels rose ~20 metres in under 500 years as Laurentide ice sheet collapsed. Coastal populations worldwide were displaced. Corresponds to the Younger Dryas termination.', source: 'Fairbanks, 1989; Deschamps et al., 2012', radius: 3 },

  // ── Mesopotamian ──────────────────────────────────────────────────────────
  { id: 'eridu', lat: 30.82, lng: 46.0, year: -4000, title: 'Eridu Genesis — Ziusudra', region: 'Sumer (Southern Iraq)', type: 'textual', tradition: 'Sumerian', desc: 'Oldest known written flood narrative. God Enki warns King Ziusudra of divine flood. Ziusudra builds a vessel and survives. Fragments recovered from Nippur.', source: 'Jacobsen, 1981', radius: 5, spread: [{ to: 'gilgamesh', year: -2600 }] },
  { id: 'atrahasis', lat: 32.0, lng: 44.0, year: -1800, title: 'Atrahasis Epic', region: 'Babylonia', type: 'textual', tradition: 'Old Babylonian (Atrahasis)', desc: 'The most complete Mesopotamian flood narrative. Atrahasis ("Exceedingly Wise") warned by Enki. Provides the fullest version of the divine council debate preceding the flood decision.', source: 'Lambert & Millard, 1969', radius: 4 },
  { id: 'gilgamesh', lat: 32.54, lng: 44.42, year: -2600, title: 'Gilgamesh Tablet XI', region: 'Babylon (Iraq)', type: 'textual', tradition: 'Akkadian/Babylonian (Gilgamesh)', desc: 'Utnapishtim recounts surviving a divine flood by building a vessel. 12+ structural parallels with Genesis. Tablet XI from Library of Ashurbanipal.', source: 'George, 2003', radius: 6, spread: [{ to: 'genesis', year: -1400 }] },
  { id: 'shuruppak', lat: 31.77, lng: 45.51, year: -2900, title: 'Shuruppak Flood Stratum', region: 'Southern Iraq', type: 'archaeological', tradition: 'Archaeological Record', desc: 'Excavations at Tell Fara reveal sterile alluvial deposit separating occupation levels. Similar flood deposits at Ur and Kish.', source: 'Woolley, 1955; Mallowan, 1964', radius: 3 },
  { id: 'kinglist', lat: 32.05, lng: 44.28, year: -2100, title: 'Sumerian King List', region: 'Sumer', type: 'archaeological', tradition: 'Sumerian', desc: 'The Weld-Blundell Prism divides history into "before the Flood" and "after the Flood." Pre-flood kings have impossibly long reigns. The Flood is treated as a historical watershed.', source: 'Weld-Blundell Prism, Ashmolean Museum', radius: 3 },

  // ── Biblical ──────────────────────────────────────────────────────────────
  { id: 'genesis', lat: 31.78, lng: 35.23, year: -1400, title: 'Genesis 6–9 — Noah\'s Ark', region: 'Israel / Judah', type: 'textual', tradition: 'Israelite (Genesis)', desc: 'God judges humanity for wickedness. Noah builds an ark. 40 days of rain. Dove and raven released. Covenant established with rainbow. Contains 9 structural elements appearing in exact sequence in Gilgamesh.', source: 'Genesis 6–9; Hebrew Bible', radius: 7, spread: [{ to: 'septuagint', year: -250 }, { to: 'quran', year: 632 }] },
  { id: 'enoch', lat: 31.74, lng: 35.46, year: -300, title: 'Book of Enoch — The Watchers', region: 'Judea', type: 'textual', tradition: 'Enochic Judaism', desc: '200 Watchers descend to Mount Hermon, teach forbidden arts, mate with women. Their giant offspring devastate the earth. God sends the Flood. Aramaic fragments confirmed by Dead Sea Scrolls.', source: 'Nickelsburg, 2001; Milik, 1976', radius: 4 },
  { id: 'septuagint', lat: 31.2, lng: 29.9, year: -250, title: 'Septuagint (LXX)', region: 'Alexandria, Egypt', type: 'textual', tradition: 'Enochic Judaism', desc: 'First Greek translation of Hebrew Bible. Contains textual variants in the Nephilim passage (Genesis 6:4) and flood dimensions. Used by early Christians and NT authors.', source: 'Septuagint, 3rd c. BCE', radius: 3 },

  // ── Hindu ─────────────────────────────────────────────────────────────────
  { id: 'matsya', lat: 26.85, lng: 80.91, year: -800, title: 'Shatapatha Brahmana — Manu & the Fish', region: 'Northern India', type: 'textual', tradition: 'Vedic (Manu)', desc: 'Vishnu incarnates as a fish (Matsya) to warn Manu of the flood. Manu builds a boat, preserves seven sages and seeds. No established transmission path from Mesopotamia at this date.', source: 'Shatapatha Brahmana 1.8.1', radius: 5 },
  { id: 'matsyapurana', lat: 25.32, lng: 82.99, year: -200, title: 'Matsya Purana', region: 'India', type: 'textual', tradition: 'Hinduism', desc: 'Expanded flood narrative. The fish grows from Manu\'s washpot to fill the ocean. Ties the vessel to the fish\'s horn with a serpent-rope.', source: 'Matsya Purana', radius: 3 },

  // ── Greek ─────────────────────────────────────────────────────────────────
  { id: 'deucalion', lat: 38.41, lng: 22.38, year: -700, title: 'Deucalion & Pyrrha', region: 'Greece (Parnassus)', type: 'textual', tradition: 'Greek', desc: 'Zeus destroys the Bronze Age with a flood. Deucalion (son of Prometheus) and Pyrrha survive in a chest. Land on Mount Parnassus. Repopulate earth by throwing stones.', source: 'Ovid, Metamorphoses I; Apollodorus', radius: 4 },

  // ── Chinese ───────────────────────────────────────────────────────────────
  { id: 'gunyu', lat: 34.75, lng: 113.65, year: -2300, title: 'Gun-Yu Flood — Emperor Yao', region: 'Yellow River Basin, China', type: 'textual', tradition: 'Chinese (Gun-Yu)', desc: 'Great flood during Emperor Yao\'s reign. Gun fails with dams; his son Yu succeeds through drainage channels. Recorded as history, not myth. Yu becomes emperor. Geological confirmation published 2016.', source: 'Sima Qian, Shiji; Wu et al. 2016', radius: 5 },

  // ── Norse ─────────────────────────────────────────────────────────────────
  { id: 'norse', lat: 64.14, lng: -21.9, year: -500, title: "Ymir's Blood — Prose Edda", region: 'Scandinavia / Iceland', type: 'textual', tradition: 'Northern European', desc: "The gods slay the primordial giant Ymir. His blood floods the world, drowning all frost giants except Bergelmir, who escapes on a vessel.", source: 'Snorri Sturluson, Prose Edda, c. 1220', radius: 3 },

  // ── Mesoamerican ─────────────────────────────────────────────────────────
  { id: 'popolv', lat: 15.0, lng: -91.0, year: -1500, title: 'Popol Vuh — Third Creation', region: "K'iche' Maya (Guatemala)", type: 'textual', tradition: "Quiché Maya", desc: 'Gods destroy wooden people with a flood of resin and rain. Third of four creation cycles. Geographically isolated from all Near Eastern traditions by an ocean.', source: 'Christenson, 2007', radius: 4 },

  // ── North American Indigenous ─────────────────────────────────────────────
  { id: 'hopi', lat: 35.83, lng: -110.57, year: -1000, title: 'Third World Destroyed by Water', region: 'American Southwest', type: 'oral_tradition', tradition: 'Hopi', desc: 'The Third World is destroyed by flood. Spider Grandmother seals the faithful inside hollow reeds that float to safety. Entirely independent from Near Eastern traditions.', source: 'Hopi Oral Tradition', radius: 4 },
  { id: 'anishinaabe', lat: 46.0, lng: -85.0, year: -1000, title: 'Anishinaabe Flood — Nanabozho', region: 'Great Lakes', type: 'oral_tradition', tradition: 'Anishinaabe (Ojibwe, Odawa, Potawatomi)', desc: 'The world is flooded; Nanabozho floats on a log. He sends diving animals to retrieve soil from the ocean floor. A muskrat succeeds. The earth is reformed on a turtle\'s back.', source: 'Anishinaabe Oral Tradition', radius: 3 },
  { id: 'klamath', lat: 42.2, lng: -121.8, year: -5700, title: 'Klamath — Crater Lake Formation', region: 'Oregon, USA', type: 'oral_tradition', tradition: 'Klamath', desc: 'Klamath oral tradition describes the battle between Llao and Skell resulting in the volcanic collapse that formed Crater Lake. Geologically dated to 5677 BCE ± 150 years. Exact match.', source: 'Nunn & Reid, 2015; Volcanic record', radius: 4 },

  // ── African ───────────────────────────────────────────────────────────────
  { id: 'yoruba', lat: 7.6, lng: 3.9, year: -500, title: 'Yoruba Flood Myth', region: 'West Africa', type: 'oral_tradition', tradition: 'Yoruba', desc: 'Olokun, the Yoruba sea deity, floods the earth in anger. A select few survive by clinging to mountains. The narrative emphasizes divine anger and survivor covenant.', source: 'Yoruba Oral Tradition', radius: 3 },

  // ── Australian Aboriginal ─────────────────────────────────────────────────
  { id: 'narrangga', lat: -34.7, lng: 137.5, year: -9000, title: 'Narrangga — Flooded Coastlines', region: 'South Australia', type: 'oral_tradition', tradition: 'Narrangga', desc: 'Oral traditions describe specific coastlines and landmarks that are now submerged 40+ metres underwater. Confirmed by bathymetric surveys. Traditions appear to encode post-glacial sea level rise.', source: 'Nunn & Reid, 2015', radius: 4 },
  { id: 'yidinji', lat: -17.0, lng: 145.7, year: -9000, title: 'Yidinji — Fitzroy Island Submersion', region: 'Queensland, Australia', type: 'oral_tradition', tradition: 'Yidinji', desc: 'Traditions describe Fitzroy Island as once connected to the mainland. The island is now separated by 6km of ocean. Geological data confirms this separation occurred ~9,000 years ago.', source: 'Nunn & Reid, 2015', radius: 3 },
  { id: 'tiwi', lat: -11.5, lng: 130.5, year: -8000, title: 'Tiwi — Bathurst Island Separation', region: 'Northern Territory, Australia', type: 'oral_tradition', tradition: 'Tiwi', desc: 'Tiwi Island oral traditions describe a time when the island was connected to the Australian mainland. Separation is dated geologically to ~8,000 years ago.', source: 'Nunn & Reid, 2015', radius: 3 },

  // ── Islamic ───────────────────────────────────────────────────────────────
  { id: 'quran', lat: 21.42, lng: 39.82, year: 632, title: 'Surah Nuh — Quran', region: 'Mecca / Medina', type: 'textual', tradition: 'Israelite (Genesis)', desc: "Surah 71 is entirely dedicated to Noah (Nuh). Key difference from Genesis: Noah's own son refuses to board the ark and drowns. The Quran's version explicitly diverges from the Hebrew account.", source: 'Quran, Surah 71; Surah Hud 11:25–49', radius: 4 },
];
