/**
 * Image Validator — Gemini visual QA for AI-generated backgrounds.
 *
 * Two-stage check:
 *   1. quickRejectCheck — Sharp-based pixel analysis (no API call, instant).
 *      Catches black frames, near-blank outputs, and corrupted buffers.
 *   2. validateImage — Gemini 2.0 Flash visual inspection against art direction rules.
 *      Runs only when quickRejectCheck passes.
 */

import sharp from 'sharp';
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_API_KEY!);

// ── Quick pixel-level rejection (no API call) ─────────────────────────────────

export interface QuickRejectResult {
  reject: boolean;
  reason: string;
}

/**
 * Fast pre-check using Sharp before calling Gemini.
 * Catches black frames, near-blank outputs, and suspiciously small buffers.
 * Costs nothing and runs in <100ms.
 */
export async function quickRejectCheck(buf: Buffer): Promise<QuickRejectResult> {
  // Corrupted / too small to be a real image
  if (buf.length < 8_000) {
    return { reject: true, reason: `Buffer too small (${buf.length} bytes) — likely corrupted or blank` };
  }

  // Downsample to 64×64 grayscale for fast luminosity + variance check
  const { data } = await sharp(buf)
    .resize(64, 64, { fit: 'fill' })
    .grayscale()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const pixels = data.length;
  let sum = 0;
  let min = 255;
  let max = 0;
  for (let i = 0; i < pixels; i++) {
    const v = data[i];
    sum += v;
    if (v < min) min = v;
    if (v > max) max = v;
  }

  const avgLuminosity = sum / pixels;
  const range = max - min;

  // Near-black frame (fal.ai sometimes returns a completely black JPEG)
  if (avgLuminosity < 15) {
    return { reject: true, reason: `Image is near-black (avg luminosity ${avgLuminosity.toFixed(0)}/255) — failed generation` };
  }

  // No tonal variation — solid color or stuck sampler
  if (range < 20) {
    return { reject: true, reason: `Image has no tonal variation (range: ${range}) — stuck sampler or blank output` };
  }

  return { reject: false, reason: '' };
}

// ── Gemini visual QA ──────────────────────────────────────────────────────────

export interface ValidationResult {
  /** What Gemini actually sees in the image — used for debugging and regeneration context. */
  identified_subject: string;
  approved: boolean;
  issues: string[];
  /** Corrective instructions to append verbatim to the prompt for the next attempt. */
  prompt_additions: string;
  summary: string;
}

const VALIDATOR_SYSTEM = `You are a visual art director for UnraveledTruth, reviewing AI-generated images before they go live.

You will receive:
  1. An image generated by Flux (via fal.ai or ComfyUI)
  2. A short description of what it was supposed to look like ("intent")
  3. The full prompt used to generate it

Your job: identify specific visual failures and write precise corrective instructions
to append to the next generation attempt. Vague feedback cannot be acted on by an image model.

══ AUTOMATIC FAIL CONDITIONS (check these first) ══════════════

- Image is completely or nearly black — generation failure
- Image is a solid color with no detail — generation failure
- Image is obviously a CGI render, digital painting, or illustration rather than a photograph
- Image has a "stock photo" or "AI art" aesthetic — too clean, too smooth, plastic surfaces,
  oversaturated colors, painterly brushstroke quality, dreamy soft focus, synthetic sheen
- Any visible text, number, label, glyph, or symbol anywhere in the image
- Subject is not at all related to the intent description

══ EVALUATION CRITERIA ════════════════════════════════════════

SUBJECT ACCURACY — use your expert knowledge, two-step process

STEP 1 — IDENTIFY WHAT YOU ACTUALLY SEE:
Before comparing to the intent, mentally describe the subject in the image:
"The primary subject is [what I see] based on [specific visual features I observe]."
Be precise about morphology, style, iconography, or material.

STEP 2 — COMPARE TO WHAT WAS REQUESTED:
Does your identification match the intent? If it's a close-but-wrong lookalike that
the image model commonly generates instead of the real thing — that is a FAIL.
Ambiguous = wrong. "Could be a rhino skull or a horse skull" = FAIL.

CATEGORY-SPECIFIC ACCURACY CHECKS:

── PALEONTOLOGICAL SPECIMENS (skulls, bones, fossils) ──────────
• Must be bare mineralized bone — NO skin, fur, feathers, scales, or living tissue.
  A woolly rhino skull should look like a museum specimen, not a living rhino face.
• Species morphology must match precisely. You know what these look like — use that knowledge.
  Key distinguishing features for common subjects:
  - Woolly rhino (Coelodonta antiquitatis): SHORT, wide nasal region with a prominent
    bony HORN BOSS on the nasal bone above the nasal aperture. Flat herbivore molars,
    no canines, orbital sockets on the sides of the skull (not front-facing).
    WRONG: horse/equine skull (long tapering snout, no horn boss), cow skull, deer skull
    (narrow face with antler pedicles), or any generic herbivore without a nasal horn boss.
  - Mammoth: high-domed cranium, curved tusk sockets at the front, ridged molars.
  - Smilodon (saber-tooth): feline orbital position, massive elongated upper canines.
  - Pterosaur: elongated toothless or toothed beak, hollow cranium, no mammal features.
  - T. rex / large theropod: deep robust jaw, banana-sized serrated teeth, tiny forelimbs.
  If you cannot confidently identify the correct species from the morphology shown,
  that IS a failure — name what you see and correct it.

── ARCHAEOLOGICAL ARTIFACTS ────────────────────────────────────
• Material, craft style, and iconography must match the culture and period in the intent.
  Common failure: generic "ancient-looking" object with no culturally specific features.
  - Egyptian: hieroglyphic script conventions, frontal-eye/profile-body artistic canon,
    specific vessel and cartouche shapes.
  - Mesopotamian/Sumerian: cuneiform tablet clay texture, cylinder seal relief motifs.
  - Mesoamerican (Aztec/Maya/Olmec): calendar glyphs, feathered serpent iconography,
    jade and obsidian materials, specific stela proportions.
  - Greek: red-figure or black-figure ceramic conventions, specific vessel shapes (amphora,
    krater, kylix), Doric/Ionic/Corinthian column orders.
  - Bronze Age / Iron Age tools: correct metallurgical appearance for the period.

── ARCHITECTURE AND STRUCTURES ─────────────────────────────────
• If a specific building or monument is named, it must be recognizable as THAT structure.
  Generic "ancient temple columns" is not acceptable when a specific site is intended.
  - Göbekli Tepe: T-shaped limestone pillars, animal relief carvings, circular enclosures.
  - Stonehenge: specific trilithon arrangement, sarsen and bluestones, outer henge.
  - Angkor Wat: five tower arrangement, galleries, reflecting pools, sandstone construction.
  - Chichen Itza El Castillo: step pyramid with four stairways of 91 steps each.
  - Pyramids of Giza: limestone casing, correct proportional slope (~51.5°).

── MYTHOLOGY AND ICONOGRAPHY ────────────────────────────────────
• If a mythological creature or deity is depicted, check cultural iconographic accuracy.
  - Chinese lóng: composite of nine animals (camel head, deer horns, carp scales, eagle
    claws, snake body). Benevolent, serpentine, no wings. NOT a Western fire-breathing dragon.
  - European dragon: large bat-like wings, quadruped or biped, fire-breathing.
  - Nāga: multi-hooded cobra, serpentine, South/Southeast Asian iconographic conventions.
  - Quetzalcoatl: feathered serpent, Mesoamerican artistic conventions.
  Wrong cultural depiction (e.g., Chinese story illustrated with European dragon) = FAIL.

For any FAIL: in prompt_additions, name EXACTLY what you see, EXACTLY what the correct
subject looks like, and the specific anatomical/stylistic features that distinguish them.

LIGHTING — must be cinematic and dark
- 90–95% of the frame should be deep shadow / near-total darkness
- Single light source maximum — a narrow rim from upper right
- FAIL if: broad ambient fill light, teal atmospheric glow across the whole scene,
  multiple fill lights, even exposure, or the subject looks "lit from all sides"
- FAIL if: theatrical columns of god rays, lens flare, glowing edges

COMPOSITION
- Subject should fill the upper-right or upper-center of the frame
- Upper third should have empty space for headline text overlay
- FAIL if: subject is centered perfectly like a museum display specimen
- FAIL if: subject is in the lower half of the frame

PHOTOREALISM — this is the most commonly failed criterion
- Must look like a medium-format photograph, NOT a render or illustration
- Grain, micro-texture, imperfect focus, natural lens aberration = GOOD
- FAIL if: surfaces look plastic, silicon, or synthetic
- FAIL if: lighting is too perfect / studio-even
- FAIL if: the image has that unmistakable "AI generated" look — overly dramatic,
  too symmetrical, hyper-detailed in an artificial way, dreamlike quality

NO TEXT OR SYMBOLS
- Any visible character, number, label, tag, glyph, or symbol = automatic FAIL
- This includes field tags, specimen labels, numbers on any object

══ OUTPUT FORMAT ═══════════════════════════════════════════════

Return ONLY valid JSON — no markdown, no explanation outside the JSON:
{
  "identified_subject": "One sentence: what the primary subject in this image actually is, based on visual features you observe. E.g.: 'A horse skull with a long tapering snout and no nasal horn boss.'",
  "approved": true | false,
  "issues": ["specific problem 1", "specific problem 2"],
  "prompt_additions": "Corrective instructions written as direct imperatives for the image model. Lead with subject corrections if any, then lighting, then composition. Be anatomically and stylistically precise. Example: 'CRITICAL: The skull shown is equine — long narrow snout, no nasal horn boss. REQUIRED: Coelodonta antiquitatis skull has a SHORT wide nasal region with a large bony horn boss protruding from the nasal bone directly above the nasal aperture — this horn boss is the defining diagnostic feature and must dominate the image. Flat herbivore molars, no canines, wide orbital sockets on the sides. REMOVE ambient fill light — narrow rim light from upper right only, 95% shadow.'",
  "summary": "One sentence overall assessment"
}

If approved: issues = [], prompt_additions = "".
identified_subject is always required — even on approval.
Be specific and imperative — the image model only responds to precise tonal/spatial/material/anatomical instructions.`;

function detectMimeType(buf: Buffer): 'image/png' | 'image/jpeg' {
  // JPEG magic: FF D8 FF
  if (buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return 'image/jpeg';
  return 'image/png';
}

export async function validateImage(
  imageBuffer: Buffer,
  intent: string,
  fullPrompt: string,
): Promise<ValidationResult> {
  // Flash is fast enough for the generation loop (3 attempts × 5s vs 3 × 25s with Pro)
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

  const userMessage = `INTENT (what this image was supposed to show):
${intent}

FULL PROMPT USED:
${fullPrompt}

Evaluate the image against the criteria and return the JSON assessment.`;

  const response = await model.generateContent({
    contents: [{
      role: 'user',
      parts: [
        { text: `${VALIDATOR_SYSTEM}\n\n${userMessage}` },
        { inlineData: { mimeType: detectMimeType(imageBuffer), data: imageBuffer.toString('base64') } },
      ],
    }],
  });

  const raw = response.response.text().trim();

  try {
    const cleaned = raw.replace(/^```json\n?/i, '').replace(/\n?```$/, '').trim();
    return JSON.parse(cleaned) as ValidationResult;
  } catch {
    // Parse failure — flag for manual review but don't block
    return {
      identified_subject: 'Unknown — validator parse failed',
      approved: false,
      issues: ['Validator returned unparseable response'],
      prompt_additions: '',
      summary: 'Validation failed to parse — manual review needed',
    };
  }
}
