import Link from 'next/link';
import type { JawDropLayer } from '@/lib/research/types';

interface TopFindingsProps {
  layers: JawDropLayer[];
  slug: string;
  /** Plain-language per-finding explanations generated by the overview pipeline.
   *  Index matches jaw_drop_layers order. Falls back to first 2 sentences of
   *  layer.content when not populated. */
  overviewExplanations?: string[];
  /** 1-2 sentence bridge from the summary into the evidence section. */
  narrativeBridge?: string | null;
  /** Two short connectors: [0] between finding 1-2, [1] between finding 2-3. */
  findingConnectors?: string[] | null;
}

function twoSentences(text: string): string {
  const sentences = text.match(/[^.!?]+[.!?]+/g) ?? [];
  return sentences.slice(0, 2).join(' ').trim();
}

/** Findings where the research tool itself is the subject (null-result / refusal findings)
 *  shouldn't appear in the overview "hard to explain away" teaser — they read as product
 *  failures to new visitors. They remain visible in the full deep-dive. */
function isMetaToolFinding(layer: JawDropLayer): boolean {
  const needle = layer.title.toLowerCase() + ' ' + layer.evidence_hook.toLowerCase();
  return (
    needle.includes('research tool') ||
    needle.includes('automated research') ||
    needle.includes('refused the assignment') ||
    needle.includes('formal refusal') ||
    needle.includes('mythology cluster')
  );
}

export function TopFindings({
  layers,
  slug,
  overviewExplanations,
  narrativeBridge,
  findingConnectors,
}: TopFindingsProps) {
  // Pair each layer with its original index so overviewExplanations stays aligned after filtering.
  const substantive = layers
    .map((l, originalIndex) => ({ layer: l, originalIndex }))
    .filter(({ layer }) => !isMetaToolFinding(layer));
  const top = substantive.slice(0, 3);
  const hiddenCount = layers.length - top.length;
  if (top.length === 0) return null;

  return (
    <section className="border-b border-border">
      <div className="max-w-[var(--spacing-content)] mx-auto px-6 py-8">
        <span className="font-mono text-[9px] tracking-[0.25em] uppercase text-text-tertiary block mb-4">
          The Evidence
        </span>

        {/* Narrative bridge — flows directly from the summary, replaces the generic h2 */}
        {narrativeBridge ? (
          <p className="text-base text-text-secondary leading-[1.85] mb-6 max-w-2xl">
            {narrativeBridge}
          </p>
        ) : (
          <h2 className="font-serif text-xl sm:text-2xl mb-6">
            The Findings That Are Hard to Explain Away
          </h2>
        )}

        <div className="max-w-2xl">
          {top.map(({ layer, originalIndex }, i) => {
            const explanation = overviewExplanations?.[originalIndex] ?? twoSentences(layer.content);
            const isLast = i === top.length - 1;
            const connector = !isLast ? (findingConnectors?.[i] ?? null) : null;

            return (
              <div key={originalIndex}>
                {/* Finding as prose — title is the bold opening sentence */}
                <div className="py-4">
                  <h3 className="font-serif text-base sm:text-[17px] text-text-primary mb-2 leading-snug">
                    {layer.title}
                  </h3>
                  <p className="text-sm text-text-secondary leading-[1.85] mb-3">
                    {explanation}
                  </p>
                  <p className="font-mono text-[10px] text-gold/70 border-l border-gold/20 pl-3 italic leading-relaxed">
                    {layer.evidence_hook}
                  </p>
                </div>

                {/* Connector between findings, or subtle rule as fallback */}
                {!isLast && (
                  connector ? (
                    <p className="text-sm text-text-tertiary/70 italic py-2">
                      {connector}
                    </p>
                  ) : (
                    <div className="border-t border-border/30 my-1" />
                  )
                )}
              </div>
            );
          })}
        </div>

        {hiddenCount > 0 && (
          <div className="mt-5">
            <Link
              href={`/topics/${slug}?view=deep#the-evidence`}
              className="font-mono text-[10px] tracking-[0.15em] uppercase text-gold/70 hover:text-gold transition-colors"
            >
              {hiddenCount} more {hiddenCount === 1 ? 'finding' : 'findings'} in the full research →
            </Link>
          </div>
        )}
      </div>
    </section>
  );
}
