import Link from 'next/link';
import type { JawDropLayer } from '@/lib/research/types';

interface TopFindingsProps {
  layers: JawDropLayer[];
  slug: string;
  /** Plain-language per-finding explanations generated by the overview pipeline.
   *  Index matches jaw_drop_layers order. Falls back to first 2 sentences of
   *  layer.content when not populated. */
  overviewExplanations?: string[];
}

function twoSentences(text: string): string {
  const sentences = text.match(/[^.!?]+[.!?]+/g) ?? [];
  return sentences.slice(0, 2).join(' ').trim();
}

export function TopFindings({ layers, slug, overviewExplanations }: TopFindingsProps) {
  const top = layers.slice(0, 3);
  if (top.length === 0) return null;

  return (
    <section className="border-b border-border">
      <div className="max-w-[var(--spacing-content)] mx-auto px-6 py-8">
        <span className="font-mono text-[9px] tracking-[0.25em] uppercase text-text-tertiary block mb-2">
          The Evidence
        </span>
        <h2 className="font-serif text-xl sm:text-2xl mb-6">
          The Findings That Are Hard to Explain Away
        </h2>
        <div className="space-y-px">
          {top.map((layer, i) => {
            const explanation = overviewExplanations?.[i] ?? twoSentences(layer.content);
            return (
              <div key={i} className="flex gap-0 border border-border bg-ground-light/20">
                <div
                  className="w-1 shrink-0"
                  style={{
                    background: i === 0
                      ? 'var(--color-gold)'
                      : i === 1
                      ? 'rgba(200,149,108,0.5)'
                      : 'rgba(255,255,255,0.1)',
                  }}
                />
                <div className="flex-1 px-5 py-4">
                  <h3 className="font-serif text-base sm:text-lg mb-2">{layer.title}</h3>
                  <p className="text-sm text-text-secondary leading-[1.8] mb-3">
                    {explanation}
                  </p>
                  <p className="font-mono text-[11px] text-gold/80 border-l-2 border-gold/25 pl-3 italic leading-relaxed">
                    {layer.evidence_hook}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
        {layers.length > 3 && (
          <div className="mt-4">
            <Link
              href={`/topics/${slug}?view=deep#the-evidence`}
              className="font-mono text-[10px] tracking-[0.15em] uppercase text-gold/70 hover:text-gold transition-colors"
            >
              {layers.length - 3} more findings in the full research →
            </Link>
          </div>
        )}
      </div>
    </section>
  );
}
