/**
 * POST /api/admin/images/generate-social
 *
 * Generates a social media image via local ComfyUI (Flux.2 Klein 4B fp8).
 * Body: { topic: string, prompt: string }
 *
 * Flow:
 *   1. Send prompt to ComfyUI
 *   2. Poll until complete
 *   3. Upload to Supabase Storage (topic-images bucket)
 *   4. Insert into topic_images with source='comfyui_generated', status='suggested'
 *
 * Returns: { ok, id, url, prompt }
 */

import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabaseClient } from '@/lib/supabase';
import { requireAdmin } from '@/lib/auth';
import { generateImageComfyUI } from '@/lib/external/comfyui';
import { COMFYUI_TAIL_BLOCK } from '@/lib/media/hero-prompt-generator';

export const maxDuration = 300;

export async function POST(req: NextRequest) {
  const { error: authError } = await requireAdmin();
  if (authError) return authError;

  const { topic, prompt } = await req.json() as { topic?: string; prompt?: string };
  if (!topic) return NextResponse.json({ error: 'topic required' }, { status: 400 });
  if (!prompt) return NextResponse.json({ error: 'prompt required' }, { status: 400 });

  const supabase = createServerSupabaseClient();

  // Apply the same art direction DNA used for Grok hero images
  const styledPrompt = prompt.trimEnd().endsWith(COMFYUI_TAIL_BLOCK.slice(-40).trim())
    ? prompt
    : `${prompt.trimEnd()} ${COMFYUI_TAIL_BLOCK}`;

  let result;
  try {
    result = await generateImageComfyUI(styledPrompt);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: `ComfyUI generation failed: ${msg}` }, { status: 500 });
  }

  // Upload to Supabase Storage
  const slug = topic.replace(/[^a-z0-9-]/gi, '_');
  const storagePath = `${slug}/social_${Date.now()}.png`;

  const { error: uploadError } = await supabase.storage
    .from('topic-images')
    .upload(storagePath, result.buffer, { contentType: 'image/png', upsert: false });

  if (uploadError) {
    return NextResponse.json({ error: `Upload failed: ${uploadError.message}` }, { status: 500 });
  }

  const { data: { publicUrl } } = supabase.storage
    .from('topic-images')
    .getPublicUrl(storagePath);

  const { data: inserted, error: dbError } = await supabase
    .from('topic_images')
    .insert({
      topic,
      source: 'comfyui_generated',
      search_query: 'social',
      title: 'Social — ComfyUI',
      description: styledPrompt,
      image_url: publicUrl,
      thumbnail_url: publicUrl,
      source_page_url: null,
      license: 'AI Generated',
      license_url: null,
      attribution: 'Generated by ComfyUI / Flux.2 Klein for UnraveledTruth.com',
      author: 'ComfyUI / Flux.2 Klein',
      date_created: new Date().toISOString().slice(0, 10),
      width: 1024,
      height: 1024,
      mime_type: 'image/png',
      quality_score: 0.80,
      status: 'suggested',
      featured: false,
      gemini_verdict: null,
      gemini_caption: null,
      gemini_literal: styledPrompt,
      updated_at: new Date().toISOString(),
    })
    .select('id')
    .single();

  if (dbError) {
    await supabase.storage.from('topic-images').remove([storagePath]);
    return NextResponse.json({ error: `DB error: ${dbError.message}` }, { status: 500 });
  }

  return NextResponse.json({ ok: true, id: inserted.id, url: publicUrl, prompt: styledPrompt });
}
